package ch.swissbytes.domain.model.entities;
// Generated 07-feb-2014 10:48:37 by Hibernate Tools 3.2.0.CR1


import javax.persistence.*;
import java.io.Serializable;

/**
 * PermissionGrantedEntity generated by hbm2java
 */
@Entity
@Table(name = "user_option", schema = "public")
public class UserPermissionGrantedEntity implements Serializable {

    private Long id;
    private OptionsEntity options;
    private UserEntity user;

    @Id
    @Column(name = "id", nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "OPTION_ID", nullable = false)
    public OptionsEntity getOptions() {
        return this.options;
    }

    public void setOptions(OptionsEntity options) {
        this.options = options;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "USER_ID", nullable = false)
    public UserEntity getUser() {
        return this.user;
    }

    public void setUser(UserEntity user) {
        this.user = user;
    }
}


