package ch.swissbytes.fqmes.model.entities;
// Generated 07-feb-2014 10:48:37 by Hibernate Tools 3.2.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * PermissionGrantedEntity generated by hbm2java
 */
@Entity
@Table(name="role_option"
        ,schema="public"
)
public class PermissionGrantedEntity implements Serializable{


     private Long id;
     private OptionsEntity options;
     private RoleEntity role;

    public PermissionGrantedEntity() {
    }

    public PermissionGrantedEntity(Long id, OptionsEntity options, RoleEntity role) {
       this.id = id;
       this.options = options;
       this.role = role;
    }
   
     @Id
    @Column(name="id", nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="OPTION_ID", nullable=false)
    public OptionsEntity getOptions() {
        return this.options;
    }
    
    public void setOptions(OptionsEntity options) {
        this.options = options;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ROLE_ID", nullable=false)
    public RoleEntity getRole() {
        return this.role;
    }
    
    public void setRole(RoleEntity role) {
        this.role = role;
    }



  // The following is extra code specified in the hbm.xml files

		    private static final long serialVersionUID = 1L;
		
  // end of extra code specified in the hbm.xml files

}


