--this scripts adds status column next tables
--@author Alvaro Cardozo.

ALTER TABLE ATTACHMENT ADD COLUMN STATUS_ID INTEGER ;
ALTER TABLE COMMENTS ADD COLUMN STATUS_ID INTEGER ;
ALTER TABLE PURCHASE_ORDER ADD COLUMN STATUS_ID INTEGER ;
ALTER TABLE SCOPE_SUPPLY ADD COLUMN STATUS_ID INTEGER;
ALTER TABLE SUPPLIER ADD COLUMN STATUS_ID INTEGER ;

UPDATE ATTACHMENT SET STATUS_ID =1 ;
UPDATE COMMENTS SET STATUS_ID =1 ;
UPDATE PURCHASE_ORDER SET STATUS_ID =1 ;
UPDATE SCOPE_SUPPLY SET STATUS_ID =1 ;
UPDATE SUPPLIER SET STATUS_ID =1 ;

ALTER TABLE ATTACHMENT ALTER COLUMN STATUS_ID SET NOT NULL ;
ALTER TABLE COMMENTS ALTER COLUMN STATUS_ID SET NOT NULL  ;
ALTER TABLE PURCHASE_ORDER ALTER COLUMN STATUS_ID SET NOT NULL  ;
ALTER TABLE SCOPE_SUPPLY ALTER COLUMN STATUS_ID SET NOT NULL ;
ALTER TABLE SUPPLIER ALTER COLUMN STATUS_ID SET NOT NULL;

ALTER TABLE ATTACHMENT ADD CONSTRAINT FK_AT_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID);
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENTS_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID);
ALTER TABLE PURCHASE_ORDER ADD CONSTRAINT FK_PO_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID);
ALTER TABLE SCOPE_SUPPLY ADD CONSTRAINT FK_SS_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID);
ALTER TABLE SUPPLIER ADD CONSTRAINT FK_SUPPLIER_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID);

