--this scripts add table to reset  password
--@author Christian Alba.

DROP TABLE IF EXISTS VERIFICATION_TOKEN CASCADE;
DROP SEQUENCE IF EXISTS VERIFICATION_TOKEN_ID_SEQ;
CREATE SEQUENCE VERIFICATION_TOKEN_ID_SEQ INCREMENT 1 START 100;
CREATE TABLE VERIFICATION_TOKEN(
  ID BIGINT NOT NULL,
  TOKEN character varying(50),
  EXPIRATION_DATE TIMESTAMP,
  VERIFIED BOOLEAN,
  USER_ID BIGINT
);
ALTER TABLE VERIFICATION_TOKEN ADD CONSTRAINT PK_TOKEN
	PRIMARY KEY (ID);
	ALTER TABLE VERIFICATION_TOKEN ADD CONSTRAINT FK_VERIFICATION_TOKEN_USERS
	FOREIGN KEY (USER_ID) REFERENCES users (ID);