
--@author Alvaro Cardozo


update TRANSIT_DELIVERY_POINT set  IS_FORECAST_SITE_DATE_CALCULATED=not IS_FORECAST_SITE_DATE_CALCULATED;
ALTER TABLE TRANSIT_DELIVERY_POINT RENAME COLUMN IS_FORECAST_SITE_DATE_CALCULATED TO IS_FORECAST_SITE_DATE_MANUAL;
