--this scripts adds status column next tables
--@author Alvaro Cardozo.


ALTER TABLE SCOPE_SUPPLY ADD COLUMN IS_FORECAST_SITE_DATE_CALCULATED BOOL;
UPDATE SCOPE_SUPPLY SET IS_FORECAST_SITE_DATE_CALCULATED=TRUE;
ALTER TABLE SCOPE_SUPPLY ALTER COLUMN IS_FORECAST_SITE_DATE_CALCULATED SET NOT NULL;

