--this scripts adds status column next tables
--@author Alvaro Cardozo.

UPDATE SCOPE_SUPPLY SET DELIVERY_LEAD_TIME_MS=null WHERE lower(DELIVERY_LEAD_TIME_MS)<>'weeks';
UPDATE SCOPE_SUPPLY SET DELIVERY_LEAD_TIME_MS=1 WHERE DELIVERY_LEAD_TIME_MS IS NOT NULL and lower(DELIVERY_LEAD_TIME_MS)='weeks';

ALTER TABLE SCOPE_SUPPLY ALTER COLUMN DELIVERY_LEAD_TIME_MS type INTEGER USING (DELIVERY_LEAD_TIME_MS::integer);
