
--@author Alvaro Cardozo
update SCOPE_SUPPLY set  IS_FORECAST_SITE_DATE_CALCULATED=not IS_FORECAST_SITE_DATE_CALCULATED;
ALTER TABLE SCOPE_SUPPLY RENAME COLUMN IS_FORECAST_SITE_DATE_CALCULATED TO IS_FORECAST_SITE_DATE_MANUAL;