--this scripts adds status column next tables
--@author Alvaro Cardozo.

ALTER TABLE COMMENTS ALTER COLUMN F_NAME type VARCHAR(255);
ALTER TABLE COMMENTS ALTER COLUMN MIME_TYPE type VARCHAR(255);


ALTER TABLE ATTACHMENT ALTER COLUMN F_NAME type VARCHAR(255);
ALTER TABLE ATTACHMENT ALTER COLUMN MIME_TYPE type VARCHAR(255);
