--this scripts adds status column next tables
--@author Alvaro Cardozo.


ALTER TABLE SCOPE_SUPPLY ADD COLUMN ACTUAL_SITE_DATE TIMESTAMP;
ALTER TABLE SCOPE_SUPPLY ADD COLUMN ACTUAL_EX_WORK_DATE TIMESTAMP;
ALTER TABLE SCOPE_SUPPLY ADD COLUMN DELIVERY_DATE TIMESTAMP;
ALTER TABLE SCOPE_SUPPLY ADD COLUMN REQUIRED_SITE_DATE TIMESTAMP;

UPDATE SCOPE_SUPPLY SET DELIVERY_DATE=CURRENT_DATE;
UPDATE SCOPE_SUPPLY SET REQUIRED_SITE_DATE=CURRENT_DATE;

ALTER TABLE SCOPE_SUPPLY ALTER COLUMN DELIVERY_DATE SET NOT NULL;
ALTER TABLE SCOPE_SUPPLY ALTER COLUMN REQUIRED_SITE_DATE SET NOT NULL;

ALTER TABLE SCOPE_SUPPLY ADD COLUMN DELIVERY_DATE_OBS VARCHAR(50);
ALTER TABLE SCOPE_SUPPLY ADD COLUMN ACTUAL_EX_WORK_DATE_OBS VARCHAR(50);
ALTER TABLE SCOPE_SUPPLY ADD COLUMN REQUIRED_SITE_DATE_OBS VARCHAR (50);
ALTER TABLE SCOPE_SUPPLY ADD COLUMN ACTUAL_SITE_DATE_OBS VARCHAR (50);

