
--@author Alvaro Cardozo

ALTER TABLE TRANSIT_DELIVERY_POINT ADD COLUMN IS_FORECAST_SITE_DATE_CALCULATED BOOL;
UPDATE TRANSIT_DELIVERY_POINT SET IS_FORECAST_SITE_DATE_CALCULATED=TRUE;
ALTER TABLE TRANSIT_DELIVERY_POINT ALTER COLUMN IS_FORECAST_SITE_DATE_CALCULATED SET NOT NULL;