--this scripts adds status column next tables
--@author Alvaro Cardozo.

ALTER TABLE SCOPE_SUPPLY ADD CONSTRAINT PK_SCOPE_SUPPLY
	PRIMARY KEY (ID);

DROP TABLE IF EXISTS TRANSIT_DELIVERY_POINT CASCADE;

CREATE SEQUENCE TRANSIT_DELIVERY_POINT_SEQ INCREMENT 1 START 100;

CREATE TABLE TRANSIT_DELIVERY_POINT(
  ID BIGINT NOT NULL,
  LOCATION VARCHAR(50) NOT NULL,
  LEAD_TIME INTEGER NOT NULL,
  MEASUREMENT_TIME INTEGER NOT NULL,
  FORECAST_DELIVERY_DATE TIMESTAMP,
  ACTUAL_DELIVERY_DATE TIMESTAMP,
  COMMENTS VARCHAR(500),
  SCOPE_SUPPLY_ID BIGINT NOT NULL,
  STATUS_ID INTEGER NOT NULL,
  LAST_UPDATE TIMESTAMP NOT NULL
);


ALTER TABLE TRANSIT_DELIVERY_POINT ADD CONSTRAINT PK_TRANSIT_DELIVERY_POINT
	PRIMARY KEY (ID);

ALTER TABLE TRANSIT_DELIVERY_POINT ADD CONSTRAINT FK_TDP
	FOREIGN KEY (SCOPE_SUPPLY_ID) REFERENCES SCOPE_SUPPLY (ID);

ALTER TABLE TRANSIT_DELIVERY_POINT ADD CONSTRAINT FK_TDP_STATUS
	FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID);