--this scripts adds last_update column next tables
--@author Alvaro Cardozo.

ALTER TABLE ATTACHMENT ADD COLUMN LAST_UPDATE TIMESTAMP ;
ALTER TABLE COMMENTS ADD COLUMN LAST_UPDATE TIMESTAMP ;
ALTER TABLE PURCHASE_ORDER ADD COLUMN LAST_UPDATE TIMESTAMP ;
ALTER TABLE SCOPE_SUPPLY ADD COLUMN LAST_UPDATE TIMESTAMP;
ALTER TABLE SUPPLIER ADD COLUMN LAST_UPDATE TIMESTAMP ;
ALTER TABLE USERS ADD COLUMN LAST_UPDATE TIMESTAMP ;

UPDATE ATTACHMENT SET LAST_UPDATE =CURRENT_DATE ;
UPDATE COMMENTS SET LAST_UPDATE =CURRENT_DATE ;
UPDATE PURCHASE_ORDER SET LAST_UPDATE =CURRENT_DATE ;
UPDATE SCOPE_SUPPLY SET LAST_UPDATE =CURRENT_DATE ;
UPDATE SUPPLIER SET LAST_UPDATE =CURRENT_DATE ;
UPDATE USERS SET LAST_UPDATE =CURRENT_DATE ;

ALTER TABLE ATTACHMENT ALTER COLUMN LAST_UPDATE SET NOT NULL ;
ALTER TABLE COMMENTS ALTER COLUMN LAST_UPDATE SET NOT NULL  ;
ALTER TABLE PURCHASE_ORDER ALTER COLUMN LAST_UPDATE SET NOT NULL  ;
ALTER TABLE SCOPE_SUPPLY ALTER COLUMN LAST_UPDATE SET NOT NULL ;
ALTER TABLE SUPPLIER ALTER COLUMN LAST_UPDATE SET NOT NULL  ;
ALTER TABLE USERS ALTER COLUMN LAST_UPDATE SET NOT NULL  ;

