DROP SEQUENCE IF EXISTS ATTACHMENT_SCOPE_SUPPLY_SEQ CASCADE;
CREATE SEQUENCE ATTACHMENT_SCOPE_SUPPLY_SEQ INCREMENT 1 START 100;
DROP TABLE IF EXISTS ATTACHMENT_SCOPE_SUPPLY CASCADE;
CREATE TABLE ATTACHMENT_SCOPE_SUPPLY(
  	ID BIGINT DEFAULT NEXTVAL(('ATTACHMENT_SCOPE_SUPPLY_SEQ'::TEXT)::REGCLASS) NOT NULL,
  	FILE_NAME VARCHAR(255)NOT NULL,
  	MIME_TYPE VARCHAR(255)NOT NULL,
  	PATH      VARCHAR(255),
  	SCOPE_SUPPLY_ID BIGINT NOT NULL,
  	FILE_ATTACHED BYTEA,
  	STATUS_ID INTEGER NOT NULL,
  	LAST_UPDATE TIMESTAMP NOT NULL
);
ALTER TABLE ATTACHMENT_SCOPE_SUPPLY ADD CONSTRAINT PK_ATTACHMENT_SS
	PRIMARY KEY (ID);
ALTER TABLE ATTACHMENT_SCOPE_SUPPLY ADD CONSTRAINT FK_AT_SS_ID
	FOREIGN KEY (SCOPE_SUPPLY_ID) REFERENCES SCOPE_SUPPLY (ID);
ALTER TABLE ATTACHMENT_SCOPE_SUPPLY ADD CONSTRAINT FK_ATSS_STATUS_ID
	FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID);




DROP SEQUENCE IF EXISTS ATTACHMENT_COMMENT_SEQ CASCADE;
CREATE SEQUENCE ATTACHMENT_COMMENT_SEQ INCREMENT 1 START 100;
DROP TABLE IF EXISTS ATTACHMENT_COMMENT CASCADE;
CREATE TABLE ATTACHMENT_COMMENT(
  	ID BIGINT DEFAULT NEXTVAL(('ATTACHMENT_COMMENT_SEQ'::TEXT)::REGCLASS) NOT NULL,
  	FILE_NAME VARCHAR(255)NOT NULL,
  	MIME_TYPE VARCHAR(255)NOT NULL,
  	PATH      VARCHAR(255),
  	COMMENT_ID BIGINT NOT NULL,
  	FILE_ATTACHED BYTEA,
  	STATUS_ID INTEGER NOT NULL,
  	LAST_UPDATE TIMESTAMP NOT NULL
);
ALTER TABLE ATTACHMENT_COMMENT ADD CONSTRAINT PK_ATTACHMENT_CMT
	PRIMARY KEY (ID);
ALTER TABLE COMMENTS ADD CONSTRAINT PK_COMMENTS
	PRIMARY KEY (ID);
ALTER TABLE ATTACHMENT_COMMENT ADD CONSTRAINT FK_AT_CMT_ID
	FOREIGN KEY (COMMENT_ID) REFERENCES COMMENTS (ID);
	ALTER TABLE ATTACHMENT_COMMENT ADD CONSTRAINT FK_ATCMT_STATUS_ID
	FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID);


INSERT INTO ATTACHMENT_COMMENT (COMMENT_ID,FILE_NAME,MIME_TYPE,FILE_ATTACHED,STATUS_ID,LAST_UPDATE) (
  SELECT ID,F_NAME,MIME_TYPE,FILE_ATTACHED,STATUS_ID,LAST_UPDATE FROM COMMENTS
    WHERE STATUS_ID=1
);



-----------------------------------------
--------------------------------------------RENAMING COLUMNS

ALTER TABLE PURCHASE_ORDER
  RENAME COLUMN DESCRIPTION to PROJECT_NAME_COMMENT;

ALTER TABLE SUPPLIER
  RENAME COLUMN ADDRESS_DESCRIPTION TO CONTACT_DETAIL;

ALTER TABLE SUPPLIER
  RENAME COLUMN CONTACT_NAME_DESCRIPTION to EMAIL_ADDRESS;

ALTER TABLE PURCHASE_ORDER
  RENAME COLUMN PO_DELIVERY_DATE_DESCRIPTION to DELIVERY_DATE_COMMENT;

ALTER TABLE PURCHASE_ORDER
  RENAME COLUMN PO_INCO_TERM_DESCRIPTION to FULL_INCO_TERM;

ALTER TABLE PURCHASE_ORDER
  RENAME COLUMN RESPONSIBLE_EXPEDITING_OBSERVATION to RFE_COMMENT;

ALTER TABLE PURCHASE_ORDER
  RENAME COLUMN INTRO_EMAIL_SENT_DESCRIPTION to INTRO_EMAIL_SENT_COMMENT;

ALTER TABLE PURCHASE_ORDER
  RENAME COLUMN REQUIRED_DATE_DESCRIPTION to REQUIRED_SITE_DATE_COMMENT;

ALTER TABLE PURCHASE_ORDER
  RENAME COLUMN ACTUAL_DATE_DESCRIPTION to ACTUAL_SITE_DATE_COMMENT;