DROP VIEW V_PURCHASE_ORDER;
CREATE OR REPLACE VIEW V_PURCHASE_ORDER AS
SELECT ROW_NUMBER() OVER () AS ID, PO.ID AS PO_ID,
	PO.PROJECT, PO.PO, PO.VARIATION, PO.PO_TITLE, S.SUPPLIER,PO.RESPONSIBLE_EXPEDITING, PO.PO_INCO_TERM, PO.PO_DELIVERY_DATE,PO.REQUIRED_DATE
   FROM PURCHASE_ORDER  PO INNER JOIN SUPPLIER S ON PO.ID=S.PURCHASE_ORDER_ID
   WHERE PO.STATUS_ID<>3
   ORDER BY CASE WHEN ISNUMERIC(PO) THEN LPAD(PO.PO, 50, '0') ELSE PO.PO END;
select * from V_PURCHASE_ORDER

DROP VIEW V_SCOPE_SUPPLY;
CREATE OR REPLACE VIEW V_SCOPE_SUPPLY AS
SELECT SS.*, CAST (DATE_PART('DAY',SS.REQUIRED_SITE_DATE- SS.SITE_DATE )AS INTEGER) AS VARIANCE,
CASE WHEN DELIVERY_LEAD_TIME_QT IS NOT NULL AND DELIVERY_LEAD_TIME_MS IS NOT NULL AND DELIVERY_LEAD_TIME_MS=0
		THEN DELIVERY_LEAD_TIME_QT
	    WHEN DELIVERY_LEAD_TIME_QT IS NOT NULL AND DELIVERY_LEAD_TIME_MS IS NOT NULL AND DELIVERY_LEAD_TIME_MS=1
		THEN DELIVERY_LEAD_TIME_QT *7
	    WHEN DELIVERY_LEAD_TIME_QT IS NOT NULL AND DELIVERY_LEAD_TIME_MS IS NOT NULL AND DELIVERY_LEAD_TIME_MS=2
		THEN DELIVERY_LEAD_TIME_QT *30
	    WHEN DELIVERY_LEAD_TIME_QT IS NOT NULL AND DELIVERY_LEAD_TIME_MS IS NOT NULL AND DELIVERY_LEAD_TIME_MS=3
		THEN DELIVERY_LEAD_TIME_QT *365
	    ELSE NULL
	END AS LEADTIMEDAYS
FROM SCOPE_SUPPLY SS INNER JOIN PURCHASE_ORDER PO ON PO.ID=SS.PURCHASE_ORDER_ID
WHERE SS.STATUS_ID<>3 AND PO.STATUS_ID<>3
ORDER BY SS.LAST_UPDATE DESC;