
DELETE FROM ROLE_OPTION;
DELETE FROM USER_ROLE ;
DELETE FROM USERS;
DELETE FROM ROLE;
DELETE FROM STATUS;
DELETE FROM OPTIONS;
DELETE FROM MODULE_ENTITY;

INSERT INTO ROLE VALUES (10,'SENIOR');
INSERT INTO ROLE VALUES (11,'JUNIOR');
INSERT INTO ROLE VALUES (12,'VISITOR');
INSERT INTO ROLE VALUES (13,'ADMINISTRATOR');

INSERT INTO STATUS VALUES(1,'ACTIVE');
INSERT INTO STATUS VALUES(2,'DISABLED');
INSERT INTO STATUS VALUES(3,'REMOVED');


INSERT INTO USERS VALUES (10,'simon.mcneal@mail.com','Simon','Mcneal','jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=',2,'simon',10,CURRENT_DATE);
INSERT INTO USERS VALUES (11,'info@swissbytes.ch','Administrator','Fqmes','jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=',1,'administrator',13,CURRENT_DATE);
INSERT INTO USERS VALUES (12,'senior.fqmes@yopmail.com','senior','Fqmes','jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=',1,'senior',10,CURRENT_DATE);
INSERT INTO USERS VALUES (13,'junior.fqmes@yopmail.com','junior','Fqmes','jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=',1,'junior',11,CURRENT_DATE);
INSERT INTO USERS VALUES (14,'visitor.fqmes@yopmail.com','visitor','Fqmes','jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=',1,'visitor',12,CURRENT_DATE);

INSERT INTO MODULE_ENTITY VALUES(1,'PURCHASE_ORDER');
INSERT INTO MODULE_ENTITY VALUES(2,'REPORT');
INSERT INTO MODULE_ENTITY VALUES(3,'USER');

-- USER
INSERT INTO OPTIONS VALUES(1,'USER_LIST',3);
INSERT INTO OPTIONS VALUES(2,'USER_CREATE',3);
INSERT INTO OPTIONS VALUES(3,'USER_UPDATE',3);
INSERT INTO OPTIONS VALUES(4,'USER_VIEW',3);
INSERT INTO OPTIONS VALUES(5,'USER_DELETE',3);

--PURCHASE ORDER

INSERT INTO OPTIONS VALUES(100,'PURCHASE_ORDER_LIST',1);
INSERT INTO OPTIONS VALUES(101,'PURCHASE_ORDER_CREATE',1);
INSERT INTO OPTIONS VALUES(102,'PURCHASE_ORDER_UPDATE',1);
INSERT INTO OPTIONS VALUES(103,'PURCHASE_ORDER_VIEW',1);
INSERT INTO OPTIONS VALUES(104,'PURCHASE_ORDER_DELETE',1);
INSERT INTO OPTIONS VALUES(105,'PURCHASE_ORDER_SPLIT_POIR',1);


--REPORT

INSERT INTO OPTIONS VALUES(200,'REPORT_LIST',1);
INSERT INTO OPTIONS VALUES(201,'REPORT_RECEIVABLE_MANIFEST',1);
INSERT INTO OPTIONS VALUES(202,'REPORT_JOB_SUMMARY',1);

--ADMINISTRATOR	
INSERT INTO ROLE_OPTION VALUES(1,1,13);
INSERT INTO ROLE_OPTION VALUES(2,2,13);
INSERT INTO ROLE_OPTION VALUES(3,3,13);
INSERT INTO ROLE_OPTION VALUES(4,4,13);
INSERT INTO ROLE_OPTION VALUES(5,5,13);
-- SENIOR
INSERT INTO ROLE_OPTION VALUES(100,100,10);
INSERT INTO ROLE_OPTION VALUES(101,101,10);
INSERT INTO ROLE_OPTION VALUES(102,102,10);
INSERT INTO ROLE_OPTION VALUES(103,103,10);
INSERT INTO ROLE_OPTION VALUES(104,104,10);
INSERT INTO ROLE_OPTION VALUES(105,105,10);
INSERT INTO ROLE_OPTION VALUES(106,200,10);
INSERT INTO ROLE_OPTION VALUES(107,201,10);
INSERT INTO ROLE_OPTION VALUES(108,202,10);
--JUNIOR

INSERT INTO ROLE_OPTION VALUES(200,100,11);
INSERT INTO ROLE_OPTION VALUES(201,102,11);
INSERT INTO ROLE_OPTION VALUES(202,103,11);
INSERT INTO ROLE_OPTION VALUES(203,105,11);
INSERT INTO ROLE_OPTION VALUES(204,200,11);
INSERT INTO ROLE_OPTION VALUES(205,201,11);
INSERT INTO ROLE_OPTION VALUES(206,202,11);

-- VISITOR

INSERT INTO ROLE_OPTION VALUES(300,100,12);
INSERT INTO ROLE_OPTION VALUES(301,103,12);